projet1/Controllers/filtreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static projet1.ModelBD;

namespace projet1.Controllers
{
    [Authorize(Roles = "admin")]

    public class filtreController : Controller
    {
        // GET: filtre
        [HttpGet]
        public ActionResult Index(string surchtext)
        {
            ModelBD bd = new ModelBD();

            return View(bd.produits.Where(x => x.title.Contains(surchtext) || surchtext == null).ToList());
       
        }
    }
}

projet1/Views/filtre/Index.cshtml
@model IEnumerable<projet1.ModelBD.produit>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<a class="btn btn-success" href="/produit/add" style="margin-bottom:20px; margin-top:20px;"><i class="fa fa-plus"></i> nouveau produit</a>
<div class="card">
    <span class="card-header">
        <form asp-controller="filtre" asp-action="index" method="get">
            <span class="btn-group">
                <input type="text" name="surchtext" class="form-control " placeholder="chercher par libellé" style="width:250px;height:30px;font-size:13px;">

                &nbsp;&nbsp;

                <button type="submit" value="rechercher...." class="btn btn-success" style="width:90px;height:30px;font-size:12px;">
                    <span class="glyphicon glyphicon-search"></span>
                    rechercher...
                </button>

            </span>

        </form>
</div>
<!-- /.card-header -->
<div class="card-body">
    <table class="table table-striped  table-bordered">
        <thead>
            <tr>
                <th>Libellé produit</th>
                <th>Description</th>
                <th>Catégorie</th>
                <th>prix</th>
                <th>Nom de propriètaire</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.title</td>
                    <td>@item.description</td>
                    <td>@item.categorie.name</td>
                    <td>@item.prix</td>
                    <td>@item.utilisateur.nom @item.utilisateur.prenom</td>
                    <td>
                        <a style="color:green;" href="@Url.Action("Add",new {item.ref_Id,item.title,item.description,item.CategorieId,item.ImageFile,item.ImagePath,item.prix,item.utilisateurId})"><i class="fas fa-edit" style="font-size:24px"></i></a>
                        <a style="color:red;" href="@Url.Action("Delete",new {id=item.ref_Id})"><i class="fas fa-trash-alt" style="font-size:24px"></i></a>
                    </td>
                </tr>

            }
        </tbody>
    </table>
</div>
<div class="card-footer clearfix">
    <ul class="pagination pagination-sm m-0 float-right">
        <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
    </ul>
</div>
</div>