projet1/Controllers/CategorieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projet1.Controllers
{
    [Authorize(Roles = "admin")]
    public class CategorieController : Controller
    {
        // GET: Categorie
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetCategorie()
        {
            using (ModelBD dc = new ModelBD())
            {
                var categorie = dc.categories.OrderBy(a => a.cat_Id).ToList();
                return Json(new { data = categorie }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult Save(int id)
        {
            ModelBD dc = new ModelBD();

            var v = dc.categories.Where(a => a.cat_Id == id).FirstOrDefault();
            return View(v);

        }

        [HttpPost]
        public ActionResult Save(ModelBD.categorie categorie1)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                using (ModelBD dc = new ModelBD())
                {
                    if (categorie1.cat_Id > 0)
                    {
                        //Edit 
                        var v = dc.categories.Where(a => a.cat_Id == categorie1.cat_Id).FirstOrDefault();
                        if (v != null)
                        {
                            v.name = categorie1.name;
                            v.description = categorie1.description;
                           
                            //return Json(new { success = true, message = "updated Successfully" }, JsonRequestBehavior.AllowGet);
                        }
                    }
                    else
                    {
                        //Save
                        dc.categories.Add(categorie1);
                        //return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                    }
                    dc.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            using (ModelBD dc = new ModelBD())
            {
                var v = dc.categories.Where(a => a.cat_Id == id).FirstOrDefault();
                if (v != null)
                {
                    return View(v);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteEmployee(int id)
        {
            bool status = false;
            using (ModelBD dc = new ModelBD())
            {
                var v = dc.categories.Where(a => a.cat_Id == id).FirstOrDefault();
                if (v != null)
                {
                    dc.categories.Remove(v);
                    dc.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

    }
}

projet1/Views/Categorie/Delete.cshtml
@model projet1.ModelBD.categorie
@{
    ViewBag.Title = "Delete";
    Layout = null;
}

@using (Html.BeginForm("Delete", "Categorie", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.cat_Id)

    <div style="text-align:center">
        <div class="form-group">
            <label> Numero de catégorie </label>
            <p>@Model.cat_Id</p>
        </div>

        <div class="form-group">
            <label>Nom de  catégorie</label>
            <p>@Model.name</p>
        </div>

        <div class="form-group">
            <label>Description</label>
            <p>@Model.description</p>
        </div>

       

        <p style="margin-top:10px">Etes-vous sur de vouloir supprimer la catégorie numero @Model.cat_Id?</p>

        <div style="text-align:center">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    </div>
}

projet1/Views/Categorie/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>


    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />

    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <style>
        span.field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div style="width:90%; margin:0 auto" class="tablecontainer">
        <a class="btn btn-success popup" href="/categorie/save/0" style="margin-bottom:20px; margin-top:20px;"><i class="fa fa-plus"></i> nouvelle catégorie </a>

        <table id="myDatatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Numero de catégorie</th>
                    <th>libellé catégorie</th>
                    <th>description de catégorie</th>


                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
        </table>
    </div>



    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>
    <script>
        $(document).ready(function () {
            var oTable = $('#myDatatable').DataTable({
                "ajax": {
                    "url": '/Categorie/GetCategorie',
                    "type": "get",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "cat_Id", "autoWidth": true },
                    { "data": "name", "autoWidth": true },
                    { "data": "description", "autoWidth": true },
                   {
                       "data": "cat_Id", "width": "50px", "render": function (data) {
                           return '<a class="popup" style="color:green;text-size:20px" href="/categorie/save/' + data + '"><i class="fas fa-edit" style="font-size:24px"></i></a>';
                        }
                    },
                    {
                        "data": "cat_Id", "width": "50px", "render": function (data) {
                            return '<a class="popup"  style="color:red;text-size:20px" href="/categorie/delete/' + data + '"><i class="fas fa-trash-alt style="font-size:24px"></i></a>';
                        }
                    }
                ]
            })
            $('.tablecontainer').on('click', 'a.popup', function (e) {
                e.preventDefault();
                OpenPopup($(this).attr('href'));
            })
            function OpenPopup(pageUrl) {
                var $pageContent = $('<div/>');
                $pageContent.load(pageUrl, function () {
                    $('#popupForm', $pageContent).removeData('validator');
                    $('#popupForm', $pageContent).removeData('unobtrusiveValidation');
                    $.validator.unobtrusive.parse('form');

                });

                $dialog = $('<div class="popupWindow" style="overflow:auto"></div>')
                    .html($pageContent)
                    .dialog({
                        draggable: false,
                        autoOpen: false,
                        resizable: false,
                        model: true,
                        title: 'Popup Dialog',
                        height: 350,
                        width: 600,
                        close: function () {
                            $dialog.dialog('destroy').remove();
                        }
                    })

                $('.popupWindow').on('submit', '#popupForm', function (e) {
                    var url = $('#popupForm')[0].action;
                    $.ajax({
                        type: "POST",
                        url: url,
                        data: $('#popupForm').serialize(),
                        success: function (data) {
                            if (data.status) {
                                $dialog.dialog('close');
                                oTable.ajax.reload();
                                $.notify(data.message, {
                                    globalPosition: "top center",
                                    className: "success"
                                })
                            }
                        }
                    })

                    e.preventDefault();
                })

                $dialog.dialog('open');
            }
        })
    </script>
</body>
</html>

projet1/Views/Categorie/Save.cshtml
@model projet1.ModelBD.categorie
@{
    ViewBag.Title = "Save";
    Layout = null;
}


@using (Html.BeginForm("Save", "Categorie", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model != null && Model.cat_Id > 0)
    {
        @Html.HiddenFor(a => a.cat_Id)
    }
    <div style="align-content:center">
        
        <div class="form-group">
            <label>libellé catégorie</label>
            @Html.TextBoxFor(a => a.name, new { @class = "form-control" ,required="required"})
          
        </div>
        <div class="form-group">
            <label>Description de catégorie</label>
            @Html.TextBoxFor(a => a.description, new { @class = "form-control" , required = "required" })
     
        </div>
        


        <div style="text-align:center">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
}