projet1/Controllers/Home1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using static projet1.ModelBD;
namespace projet1.Controllers
{
    
    public class Home1Controller : Controller
    {
        ModelBD model = new ModelBD();
        public ActionResult Index()
        {
            var produitsList = model.produits.ToList().Take(7);
            DateTime today = DateTime.Today;
            //client client = model.clients.Find(36);
           // proprietaire proprietaire = model.proprietaires.Find(34);
            /* var conversation = new conversation() { client = client, proprietaire = proprietaire };
             var message = new message() { text="hi do you offer a refund",conversation = conversation, date = today.ToString(), fromClient=true};
             conversation.LastMessage = message.text;
             conversation.LastMessageDate = message.date;
             model.conversations.Add(conversation);
             model.messages.Add(message);
             model.SaveChanges();*/

           // var particulier1 = model.proprietaires.Find(34);
            /*commande commande1 = new commande() { date = today.ToString(), montant = 22, quantite = 2, client = client };
            commande commande2 = new commande() { date = today.ToString(), montant = 32, quantite = 1, client = client };
            model.commandes.Add(commande2);
            model.commandes.Add(commande1);
            model.SaveChanges();
            
            var categorie1 = new categorie() { name = "parfums", description = "parfums agreables" };
            var categorie2 = new categorie() { name = "tech accessories", description = "technologies stuff" };
            
            var categorie1 = model.categories.Find(2);
            var produit1 = new produit() { proprietaire=particulier1,title = "apple airpods 3 generation", prix = 19, description = "Les AirPods vont changer à jamais votre façon d’utiliser des écouteurs. Une fois sortis de leur boîtier de charge, ils s’utilisent avec tous vos ",categorie=categorie1};
            var produit2 = new produit() { proprietaire = particulier1, title = "sauvage parfum homme", prix = 18, description = "Masculine and confident, the new Eros Eau de Parfum is a fragrance for a bold, passionate man. The sensual scent fuses woody, oriental and fresh", categorie = categorie1 };
            var produit3 = new produit() { proprietaire = particulier1, title = "Dior EAU SAUVAGE PARFUM ", prix = 18, description = "Dior EAU SAUVAGE PARFUM " , categorie = categorie1 };
            var produit4 = new produit() { proprietaire = particulier1, title = "BLEU DE CHANEL MINIATURE", prix = 18, description = "CHANEL BLEU DE CHANEL MINIATURE EAU DE PARFUM POUR HOMME 10 ML VIP GIFT", categorie = categorie1 };
            var produit5 = new produit() { proprietaire = particulier1, title = "Christian Dior Sauvage ", prix = 18, description = "Christian Dior Sauvage Edp Eau de Parfum", categorie = categorie1 };
            var produit6 = new produit() { proprietaire = particulier1, title = "BLEU DE CHANEL MINIATURE", prix = 18, description = "CHANEL BLEU DE CHANEL MINIATURE EAU DE PARFUM POUR HOMME 10 ML VIP GIFT", categorie = categorie1 };
            var produit7 = new produit() { proprietaire = particulier1, title = "dior sauvage eau de parfum", prix = 18, description = "dior sauvage eau de parfum", categorie = categorie1 };
           

            model.produits.Add(produit1);
            model.produits.Add(produit2);
            model.produits.Add(produit3);
            model.produits.Add(produit4);
            model.produits.Add(produit5);
            model.produits.Add(produit6);
            model.produits.Add(produit7);
            model.SaveChanges();
            */
            //var utilisateur2 = new utilisateur() { nom="ahmed",prenom="sam",email="ahmed@gmail.com",tel="06666666"};
            //model.utlisateurs.Add(utilisateur2);
            //model.SaveChanges();

            return View(produitsList);
           // return View();
        }
        [HttpPost]
        public ActionResult SignUp(utilisateur user1, string cin, string SIRN, string type_activite)
        {
            if (ModelState.IsValid)
            {
                using (var model = new ModelBD())
                {
                    if (Request["type"] == "client")
                    {
                        client client = new client(user1);
                        client.status = client.Status.normal;
                        client.dateAjout = DateTime.Now;
                        client.Role = "client";
                        model.clients.Add(client);
                        panier panier = new panier() { client = client };
                        model.paniers.Add(panier);
                        model.SaveChanges();
                    }
                    else if (Request["type"] == "particulier")
                    {
                        proprietaire proprietaire = new proprietaire(user1);
                        particulier particulier = new particulier(proprietaire, cin);
                        particulier.dateAjout = DateTime.Now;
                        particulier.Role = "proprietaire";
                        model.particuliers.Add(particulier);
                        model.SaveChanges();
                    }
                    else
                    {
                        proprietaire proprietaire = new proprietaire(user1);
                        societe societe = new societe(proprietaire, SIRN, type_activite);
                        societe.dateAjout = DateTime.Now;
                        societe.Role = "proprietaire";
                        model.societes.Add(societe);
                        model.SaveChanges();
                    }
                }
            }
            return RedirectToAction("Login");
        }
        public ActionResult SignUp()
        {
            if (Request.IsAuthenticated)
                return Redirect(Url.Action("Index", "Client"));
            else
                return View();
        }
        public ActionResult Login()
        {
            if(Roles.IsUserInRole(User.Identity.Name,"client"))
                return Redirect(Url.Action("Index", "Client1"));
            else if(Roles.IsUserInRole(User.Identity.Name, "proprietaire"))
                return Redirect(Url.Action("Index", "HomeProp"));
            else if(Roles.IsUserInRole(User.Identity.Name, "admin"))
                return Redirect(Url.Action("Index", "Client"));
            //ViewBag.error = TempData["LoginError"];
            else
                return View();
        }
        [HttpPost]
        public ActionResult Login(string email, string password, string returnUrl)
        {
            if (model.clients.Any(u => u.email == email && u.password == password))
            {
                FormsAuthentication.SetAuthCookie(email, false);
                return RedirectToAction("Index");

            }
            else if(model.proprietaires.Any(u => u.email == email && u.password == password))
            {
                FormsAuthentication.SetAuthCookie(email, false);
                return RedirectToAction("Index","HomeProp");
            }else if(email=="admin@shop.com" && password == "admin")
            {
                FormsAuthentication.SetAuthCookie(email, false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["LoginError"] = "email ou mot de pass incorrect";
                return Redirect(returnUrl);
            }
        }
        public ActionResult Product(int id)
        {

            var product = model.produits.Find(id);
            return View(product);
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        
        public ActionResult Search(string title)
        {
            var produits = model.produits.Where(p => p.title.Contains(title)).ToList();
            return View(produits);
        }
       
        public ActionResult SearchByCategory(string category)
        {
            var produits = model.produits.Where(p => p.categorie.name == category);
            return View(produits);
        }
    }
}

projet1/Views/Home1/Index.cshtml
@model IEnumerable<ModelBD.produit>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<html>
<head>
    <title>Home</title>
    <script src="~/Scripts/home.js" defer></script>
    <link rel="stylesheet" href="~/Content/home.css" />
</head>
<body>
    <header class="hero-section">
        <div class="content">
            <img src="~/Content/resources/light-logo.png" class="logo" alt="">
            <p class="sub-heading">best fashion collection of all time</p>
        </div>
    </header>
    <section class="product">
        <h2 class="product-category">New Offers</h2>
        <button class="pre-btn"><img src="~/Content/resources/arrow.png" alt=""></button>
        <button class="nxt-btn"><img src="~/Content/resources/arrow.png" alt=""></button>
        <div class="product-container">
            @foreach (var item in Model)
            {
                <div class="product-card">
                    <form action="/Home1/Product" id="open_product">
                    </form>
                    <div class="product-image">
                        <span class="discount-tag">50% off</span>
                        <img src="@item.ImagePath.Replace("~","")" class="product-thumb" alt="">

                        <button type="submit" form="open_product" name="id" value="@item.ref_Id" class="card-btn" formtarget="_blank">ouvrir</button>
                    </div>
                    <div class="product-info">

                        <p class="product-short-des">@item.title</p>
                        <span class="price">$@item.prix</span><span class="actual-price">${@item.prix +20}</span>
                    </div>
                </div>
            }
            <!--


             <div class="product-card">
                 <div class="product-image">
                     <span class="discount-tag">50% off</span>
                     <img src="~/Content/resources/card2.png" class="product-thumb" alt="">
                     <button class="card-btn">add to whislist</button>
                 </div>
                 <div class="product-info">

                     <p class="product-short-des">a short line about the cloth..</p>
                     <span class="price">$20</span><span class="actual-price">$40</span>
                 </div>
             </div>
             <div class="product-card">
                 <div class="product-image">
                     <span class="discount-tag">50% off</span>
                     <img src="~/Content/resources/card3.png" class="product-thumb" alt="">
                     <button class="card-btn">add to whislist</button>
                 </div>
                 <div class="product-info">

                     <p class="product-short-des">a short line about the cloth..</p>
                     <span class="price">$20</span><span class="actual-price">$40</span>
                 </div>
             </div>
             <div class="product-card">
                 <div class="product-image">
                     <span class="discount-tag">50% off</span>
                     <img src="~/Content/resources/card4.png" class="product-thumb" alt="">
                     <button class="card-btn">add to whislist</button>
                 </div>
                 <div class="product-info">

                     <p class="product-short-des">a short line about the cloth..</p>
                     <span class="price">$20</span><span class="actual-price">$40</span>
                 </div>
             </div>
             <div class="product-card">
                 <div class="product-image">
                     <span class="discount-tag">50% off</span>
                     <img src="~/Content/resources/card5.png" class="product-thumb" alt="">
                     <button class="card-btn">add to whislist</button>
                 </div>
                 <div class="product-info">

                     <p class="product-short-des">a short line about the cloth..</p>
                     <span class="price">$20</span><span class="actual-price">$40</span>
                 </div>
             </div>
             <div class="product-card">
                 <div class="product-image">
                     <span class="discount-tag">50% off</span>
                     <img src="~/Content/resources/card6.png" class="product-thumb" alt="">
                     <button class="card-btn">add to whislist</button>
                 </div>
                 <div class="product-info">

                     <p class="product-short-des">a short line about the cloth..</p>
                     <span class="price">$20</span><span class="actual-price">$40</span>
                 </div>
             </div>
             <div class="product-card">
                 <div class="product-image">
                     <span class="discount-tag">50% off</span>
                     <img src="~/Content/resources/card7.png" class="product-thumb" alt="">
                     <button class="card-btn">add to whislist</button>
                 </div>
                 <div class="product-info">

                     <p class="product-short-des">a short line about the cloth..</p>
                     <span class="price">$20</span><span class="actual-price">$40</span>
                 </div>
             </div>
            -->
        </div>
    </section>
    <section class="collection-container">
        <button value="Women Apparel" name="category" type="submit" form="search_form" class="collection">
            <img src="~/Content/resources/women-collection.png" alt="">
            <p class="collection-title">women <br> apparels</p>
        </button>
        <button type="submit" name="category" form="search_form" value="Men Apparel" class="collection">
            <img src="~/Content/resources/men-collection.png" alt="">
            <p class="collection-title">men <br> apparels</p>
        </button>
        <button value="Men's Accessories" name="category" type="submit" form="search_form" class="collection">
            <img src="~/Content/resources/accessories-collection.png" alt="">
            <p class="collection-title">accessories</p>
        </button>
        <form action="/Home1/searchByCategory" id="search_form" method="post">
            <input type="hidden" name="byCategory" value="1" />
        </form>
    </section>
</body>
</html>

projet1/Views/Home1/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<html>
<head>
    <style>
        .logo {
            height: 80px;
            display: block;
            margin: 0 auto 50px;
        }

        .container div {
            width: 400px;
            display: block;
            margin: 0 auto;
        }

        input[type="text"],
        input[type="password"],
        input[type="email"],
        textarea {
            display: block;
            width: 300px;
            height: 40px;
            padding: 20px;
            border-radius: 5px;
            background: #fff;
            border: none;
            outline: none;
            margin: 20px 0;
            color: #383838;
            font-size: 14px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.01);
            font-family: 'roboto', sans-serif;
        }

        select {
            display: block;
            width: 300px;
            height: 40px;
            padding: 0 20px;
            border-radius: 5px;
            background: #fff;
            text-transform: capitalize;
            border: none;
            outline: none;
            color: #383838;
            font-size: 14px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.01);
            font-family: 'roboto', sans-serif;
        }

        ::placeholder {
            color: #383838;
        }

        div .btns {
            width: 400px;
            display: flex;
            justify-content: space-around;
        }

        .submit-btn {
            width: 100%;
            height: 40px;
            text-align: center;
            line-height: 40px;
            background: #383838;
            color: #fff;
            border-radius: 2px;
            text-transform: capitalize;
            border: none;
            cursor: pointer;
            display: block;
            margin: 30px 0;
            transition: display 3s ease;
        }


        /* checkbox styles */

        .checkbox {
            -webkit-appearance: none;
            position: relative;
            width: 15px;
            height: 15px;
            border-radius: 2px;
            background: #fff;
            border: 1px solid #383838;
            cursor: pointer;
        }

            .checkbox:checked {
                background: #383838;
            }

            .checkbox::after {
                content: '';
                position: absolute;
                top: 60%;
                left: 50%;
                transform: translate(-50%, -50%);
                width: 80%;
                height: 100%;
                pointer-events: none;
                background-image: url(../img/check.png);
                background-size: contain;
                background-repeat: no-repeat;
                display: none;
            }

            .checkbox:checked::after {
                display: block;
            }

        label {
            text-transform: capitalize;
            display: inline-block;
            margin-bottom: 10px;
            font-size: 14px;
            color: #383838;
        }

            label a {
                color: #383838;
            }

        .link {
            color: #383838;
            text-transform: capitalize;
            text-align: center;
            display: block;
        }
    </style>
</head>
<body>
    <div class="container">
        <img src="~/Content/resources/dark-logo.png" class="logo" alt="">
        <p>@ViewBag.error</p>
        <div>
            @using (Html.BeginForm("Login", "Home1", new { returnUrl = Request.Url.PathAndQuery }, FormMethod.Post))
            {

                <input type="email" autocomplete="off" id="email" placeholder="email" name="email" required>
                <input type="password" autocomplete="off" id="password" placeholder="password" name="password" required>
                <div class="btns">
                    <button id="log in" class="submit-btn" name="login" value="log in">log in</button>

                </div>

            }
        </div>
        <a href="SignUp" class="link">dont have an account? Sign up here</a>
    </div>
</body>
</html>

projet1/Views/Home1/Product.cshtml
@model ModelBD.produit
@{
    ViewBag.Title = "Product";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<html>
<head>
    <link rel="stylesheet" href="~/Content/product_page.css" />
    <script src="~/Scripts/product_page.js" defer></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
</head>
<body>
    <div class="contact_form">
        <div class="head">Envoyer un message</div>
        <div class="body_form">
            <div class="profil">
                <button>
                    <img src="~/Content/resources/authenticated.png" />
                </button>
                <h4>@Model.utilisateur.nom</h4>
            </div>
            <form class="message" action="/client1/contact">
                <textarea name="message">

                     </textarea>
                <button name="proprietaireId" value="@Model.utilisateur.id">Envoyer</button>
                
            </form>
        </div>
    </div>
    <section class="product-details">
        <div class="image-slider">
            <div class="product-images">
                <img src="@Model.ImagePath.Replace("~","")" class="active" alt="">
                <!--
        <img src="~/Content/resources/product image 2.png" alt="">
     <img src="~/Content/resources/product image 3.png" alt="">
     <img src="~/Content/resources/product image 4.png" alt="">
    -->
            </div>
        </div>
        <div class="details">
            <form action="/Client1/AjouterPanier" id="myForm" method="post">
                <input type="hidden" name="id" value="@Model.ref_Id" />
            </form>
            <h2 class="product-brand">@Model.title</h2>
            <p class="product-short-des">@Model.subtitle</p>
            <span class="product-price">$@Model.prix </span>
            <span class="product-actual-price">$200</span>
            <span class="product-discount">( 50% off )</span>

            <p class="product-sub-heading">choisir taille</p>

            <input form="myForm" type="radio" name="size" value="S" hidden id="m-size">
            <label for="m-size" class="size-radio-btn">S</label>
            <input form="myForm" type="radio" name="size" value="M" hidden id="l-size">
            <label for="l-size" class="size-radio-btn">M</label>
            <input form="myForm" type="radio" name="size" value="L" hidden id="xl-size">
            <label for="xl-size" class="size-radio-btn">L</label>
            <input form="myForm" type="radio" name="size" value="XL" hidden id="xxl-size">
            <label for="xxl-size" class="size-radio-btn">XL</label>

            <button type="submit" form="myForm" class="btn">J'ACHETE</button>
            <button type="button" class="btn" id="contacter" name="proprietaireId">Contacter</button>


        </div>
    </section>
    <section class="detail-des">
        <h2 class="heading">description</h2>
        <p class="des">@Model.description</p>
    </section>

</body>
</html>

projet1/Views/Home1/SignUp.cshtml
@model projet1.ModelBD.utilisateur
@{ ViewBag.Title = "SignUp";
                Layout = "~/Views/Shared/_Layout1.cshtml"; }

<html>
<head>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/script_signup.js" defer></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <style>
        .logo {
            height: 80px;
            display: block;
            margin: 0 auto 50px;
        }

        .container div {
            width: 400px;
            display: block;
            margin: 0 auto;
        }

        input[type="text"],
        input[type="password"],
        input[type="email"],
        textarea {
            display: block;
            width: 300px;
            height: 40px;
            padding: 20px;
            border-radius: 5px;
            background: #fff;
            border: none;
            outline: none;
            margin: 20px 0;
            text-transform: capitalize;
            color: #383838;
            font-size: 14px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.01);
            font-family: 'roboto', sans-serif;
        }

        select {
            display: block;
            width: 300px;
            height: 40px;
            padding: 0 20px;
            border-radius: 5px;
            background: #fff;
            text-transform: capitalize;
            border: none;
            outline: none;
            color: #383838;
            font-size: 14px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.01);
            font-family: 'roboto', sans-serif;
        }

        ::placeholder {
            color: #383838;
        }

        div .btns {
            width: 400px;
            display: flex;
            justify-content: space-around;
        }

        .submit-btn {
            width: 100%;
            height: 40px;
            text-align: center;
            line-height: 40px;
            background: #383838;
            color: #fff;
            border-radius: 2px;
            text-transform: capitalize;
            border: none;
            cursor: pointer;
            display: block;
            margin: 30px 0;
            transition: display 3s ease;
        }


        /* checkbox styles */

        .checkbox {
            -webkit-appearance: none;
            position: relative;
            width: 15px;
            height: 15px;
            border-radius: 2px;
            background: #fff;
            border: 1px solid #383838;
            cursor: pointer;
        }

            .checkbox:checked {
                background: #383838;
            }

            .checkbox::after {
                content: '';
                position: absolute;
                top: 60%;
                left: 50%;
                transform: translate(-50%, -50%);
                width: 80%;
                height: 100%;
                pointer-events: none;
                background-image: url(../img/check.png);
                background-size: contain;
                background-repeat: no-repeat;
                display: none;
            }

            .checkbox:checked::after {
                display: block;
            }

        label {
            text-transform: capitalize;
            display: inline-block;
            margin-bottom: 10px;
            font-size: 14px;
            color: #383838;
        }

            label a {
                color: #383838;
            }

        .link {
            color: #383838;
            text-transform: capitalize;
            text-align: center;
            display: block;
        }


        .field-validation-error {
            color: red;
        }
    </style>
</head>

<body>
    <div class="container">
        <img src="~/Content/resources/dark-logo.png" class="logo" alt="">
        <div>
            @using (Html.BeginForm("SignUp", "Home1", FormMethod.Post))
            {
            <div class="form-group">
                @Html.TextBoxFor(a => a.nom, new { @class = "form-control field-validation-error", placeholder = "nom" })
                @*
        <input type="text" autocomplete="off" id="name" placeholder="name" name="nom">
                *@
                @Html.ValidationMessageFor(a => a.nom)
            </div>
                <div class="form-group">
                    @Html.TextBoxFor(a => a.prenom, new { @class = "form-control field-validation-error", placeholder = "Prenom" })
                    @Html.ValidationMessageFor(a => a.prenom)
                </div>
                                <div class="form-group">
                                    @Html.TextBoxFor(a => a.email, new { @class = "form-control field-validation-error", placeholder = "Email" })
                                    @Html.ValidationMessageFor(a => a.email)
                                </div>
                                                <div class="form-group">
                                                    @Html.TextBoxFor(a => a.password, new { @class = "form-control field-validation-error", placeholder = "Password" })
                                                </div>
                                                                <div class="form-group">
                                                                    @Html.TextBoxFor(a => a.passwordComfirm, new { @class = "form-control", placeholder = "confirmer le mot de passe" })
                                                                    @Html.ValidationMessageFor(a => a.passwordComfirm)
                                                                </div>
                                                                                <div class="form-group">
                                                                                    @Html.TextBoxFor(a => a.tel, new { @class = "form-control field-validation-error", placeholder = "numero de telephone" })
                                                                                    @Html.ValidationMessageFor(a => a.tel)
                                                                                </div>
                                                                                                <input type="text" style="display:none" autocomplete="off" id="cin" placeholder="cin" name="CIN">
                                                                                                                <input type="text" style="display:none" autocomplete="off" id="SIRN" placeholder="SIRN" name="SIRN">
                                                                                                                                <input type="text" style="display:none" autocomplete="off" id="type_activite" placeholder="type_actvite" name="type_activite">
                                                                                                                                                <select id="select_type">

                                                                                                                                                    <option value="client">client</option>
                                                                                                                                                    <option value="particulier">prorietaire (particulier)</option>
                                                                                                                                                    <option value="societe">prorietaire (societe)</option>
                                                                                                                                                </select>
                                                                                                                                                                <div class="btns">
                                                                                                                                                                    <button id="client" class="submit-btn" name="type" value="client">créer client</button>
                                                                                                                                                                    <button id="particulier" class="submit-btn" name="type" value="particulier" style="display:none">créer particulier</button>
                                                                                                                                                                    <button id="societe" class="submit-btn" name="type" value="societe" style="display:none">créer societe</button>
                                                                                                                                                                </div>}
        </div>
        <a href="/Home1/login" class="link">already have an account? Log in here</a>
    </div>
</body>

</html>